spring:
  application:
    name: sang-eu
server:
  port: 10086

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone : http://127.0.0.1:${server.port}/eureka
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 1000